version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env

    environment:
      - DATABASE_URL=postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOSTNAME:$POSTGRES_PORT/$POSTGRES_DB?async_fallback=True
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - $APP_PORT:$APP_PORT

    depends_on:
      - app_db

  app_db:
    container_name: app_db
    hostname: $POSTGRES_HOSTNAME
    image: postgres:14
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - $REDIS_PORT:$REDIS_PORT

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_main
