"""refactor file structure2

Revision ID: 5b896debe6f5
Revises: a240ad92edef
Create Date: 2023-01-14 11:57:18.813932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b896debe6f5"
down_revision = "a240ad92edef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
