"""new docker file

Revision ID: 36fd63965889
Revises: c6cf281c2393
Create Date: 2023-01-15 09:41:03.078008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36fd63965889"
down_revision = "c6cf281c2393"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
