"""uniqe constraint

Revision ID: 73e504621b2e
Revises: 36fd63965889
Create Date: 2023-01-15 20:03:24.383458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73e504621b2e"
down_revision = "36fd63965889"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("jobs_work_name_key"), "jobs", ["work_name", "unit_of_measurement"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("jobs_work_name_key"), "jobs", type_="unique")
    # ### end Alembic commands ###
