"""workers

Revision ID: 203b36d9765b
Revises: 77cef66d7fbc
Create Date: 2023-01-20 10:13:49.549873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "203b36d9765b"
down_revision = "77cef66d7fbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("speciality", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("workers_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workers")
    # ### end Alembic commands ###
