"""table naem

Revision ID: 4951f39e4456
Revises: 73e504621b2e
Create Date: 2023-01-18 21:49:59.828108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4951f39e4456"
down_revision = "73e504621b2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_tb",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("work_name", sa.String(length=200), nullable=False),
        sa.Column("unit_of_measurement", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("jobs_tb_pkey")),
        sa.UniqueConstraint(
            "work_name", "unit_of_measurement", name=op.f("jobs_tb_work_name_key")
        ),
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("work_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "unit_of_measurement", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="jobs_pkey"),
        sa.UniqueConstraint(
            "work_name", "unit_of_measurement", name="jobs_work_name_key"
        ),
    )
    op.drop_table("jobs_tb")
    # ### end Alembic commands ###
