"""refactor file structure

Revision ID: a240ad92edef
Revises: ee26c5736903
Create Date: 2023-01-14 11:20:02.027473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a240ad92edef"
down_revision = "ee26c5736903"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
