"""test4

Revision ID: ed3fd9f172c6
Revises: dfe396a9d979
Create Date: 2023-01-14 08:12:33.257606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed3fd9f172c6"
down_revision = "dfe396a9d979"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
