"""add table

Revision ID: 77cef66d7fbc
Revises: 3ad9a0bb2859
Create Date: 2023-01-19 07:54:42.280992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77cef66d7fbc"
down_revision = "3ad9a0bb2859"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objects",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("adress", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("objects_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("objects")
    # ### end Alembic commands ###
