"""test3

Revision ID: dfe396a9d979
Revises: 86b9fcab69ac
Create Date: 2023-01-14 07:31:50.191879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfe396a9d979"
down_revision = "86b9fcab69ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
