"""15.01

Revision ID: c6cf281c2393
Revises: 139bd5d8e218
Create Date: 2023-01-15 08:58:16.923712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6cf281c2393"
down_revision = "139bd5d8e218"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
