"""test module

Revision ID: 5854cbb54436
Revises: 5b896debe6f5
Create Date: 2023-01-14 16:01:26.683472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5854cbb54436"
down_revision = "5b896debe6f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
