"""test44x4

Revision ID: ee26c5736903
Revises: ecc810e1da4b
Create Date: 2023-01-14 10:58:47.620102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee26c5736903"
down_revision = "ecc810e1da4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
